dist: trusty
sudo: false
 
language: node_js
node_js:
  - "8"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  git:
    depth: false
    quiet: true
    
 
cache:
  directories:
     - ./node_modules
 
install:
  - npm install
 
script:
  - ng lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --configuration=ci

deploy:
  provider: script
  script: bash scripts/deploy.sh stage
  on:
    branch: master